# Generated by Django 5.2.3 on 2025-07-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-year", "-month"],
                "unique_together": {("month", "year")},
            },
        ),
        migrations.CreateModel(
            name="SalaryStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly basic salary",
                        max_digits=10,
                    ),
                ),
                (
                    "housing_allowance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "income_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Calculated monthly income tax",
                        max_digits=10,
                    ),
                ),
                (
                    "provident_fund",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Employee's contribution",
                        max_digits=10,
                    ),
                ),
                (
                    "other_deductions",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_structure",
                        to="employees.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "basic_salary_paid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "housing_allowance_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "transport_allowance_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_allowances_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "income_tax_deducted",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "provident_fund_deducted",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "other_deductions_made",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_deductions_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "net_salary_paid",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("generated_on", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payslips",
                        to="employees.employee",
                    ),
                ),
                (
                    "pay_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payslips",
                        to="payroll.payperiod",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-pay_period__year",
                    "-pay_period__month",
                    "employee__last_name",
                ],
                "unique_together": {("employee", "pay_period")},
            },
        ),
    ]
